services:
  terraform:
    image: tugboatqa/httpd:2.4
  
    commands:
      init:
        - wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
        - unzip ./terraform_0.11.10_linux_amd64.zip
        - rm ./terraform_0.11.10_linux_amd64.zip
        - ln -sf ./terraform /usr/local/bin/terraform
        
      build:
        - ./terraform init
